---
- name: Set fact for interface name to bring down
  set_fact:
    _target_if_name: "{{ validation.vm_ha.if_down_params.interface_name }}"

- name: Bring down the {{ _target_if_name }} interface to simulate error
  ansible.builtin.command: ip link set dev {{ _target_if_name }} down
  async: 15
  poll: 0
  ignore_errors: true

- block:
    - name: Check connectivity for reference or timeout (prevent hang)
      ansible.builtin.wait_for:
        timeout: 10
        host: "{{ ansible_host }}"
        port: 22
        state: started
      delegate_to: localhost
      ignore_errors: true

    - name: Ensure play continues even if connectivity is lost
      meta: clear_host_errors
